/* AutoForge static demo. Browser localStorage substitutes for an API/database in this demo. */
const AF={get:(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),money:n=>'₹'+Number(n).toLocaleString('en-IN'),id:()=>`AF${Date.now().toString().slice(-7)}`};
function seed(){let u=AF.get('af_users',[]);if(!u.length){u=[{name:'Demo Driver',email:'demo@autoforge.in',phone:'9867243779',password:'Demo@1234',admin:false},{name:'AutoForge Admin',email:'admin@autoforge.in',phone:'9867243779',password:'Admin@1234',admin:true}];AF.set('af_users',u)}if(!AF.get('af_orders',[]).length)AF.set('af_orders',[{id:'AF-10248',tracking:'AF-IN-000482',email:'demo@autoforge.in',items:[{id:'ceramic-9h',qty:1}],total:2499,address:'12 Lake View Road, Mumbai 400001',timestamp:'2026-09-17T09:30:00',status:'Shipped',location:'Nagpur Hub',checkpoints:['Mumbai · 17 Sep, 10:00 · Order packed','Nagpur Hub · 19 Sep, 15:40 · In transit','Your city · Expected 22 Sep']}]);}
seed(); const user=()=>AF.get('af_session',null), products=()=>window.AutoForgeProducts||[]; const product=id=>products().find(x=>x.id===id);
function image(p){return `<div class="product-image"><img loading="lazy" src="${p.image}" alt="${p.name}" onerror="this.style.display='none';this.nextElementSibling.hidden=false"><div class="fallback" hidden><span>AUTOFORGE</span><b>${p.name}</b><small>Product image arriving soon</small></div></div>`}
function shell(){let u=user(), admin=location.pathname.includes('/admin/'),root=admin?'../':'';document.getElementById('siteHeader').innerHTML=`<div class="notice">INDIA-WIDE DELIVERY · FITMENT CHECK BEFORE DISPATCH</div><header class="site-header"><div class="shell topbar"><a class="wordmark" href="${root}index.html">AUTO<i>FORGE</i></a><button class="menu" aria-label="Open navigation">☰</button><form class="search" onsubmit="event.preventDefault();location.href='${root}accessories.html?q='+encodeURIComponent(this.q.value)"><input name="q" aria-label="Search products" placeholder="Search products or car model"><button>SEARCH</button></form><button class="cart-button" onclick="toggleCart()">CART (<span id="cartCount">0</span>)</button></div><nav class="shell nav"><a href="${root}index.html">Home</a><a href="${root}accessories.html">Accessories</a><a href="${root}car-care.html">Car Care</a><a href="${root}services.html">Doorstep Services</a>${u?`<a href="${root}account.html">Hi, ${u.name.split(' ')[0]}</a><a href="#" onclick="logout()">Logout</a>`:`<a href="${root}login.html">Login</a>`}</nav></header>`;document.getElementById('siteFooter').innerHTML=`<footer class="footer"><div class="shell footer-inner"><div><div class="wordmark">AUTO<i>FORGE</i></div><p>Accessories that fit, and care that performs.</p></div><small>FITMENT & ORDER SUPPORT<br>+91 98672 43779</small></div></footer>`;document.body.insertAdjacentHTML('beforeend',`<div class="backdrop" onclick="toggleCart(false)"></div><aside class="drawer" id="cartDrawer"><div class="drawer-head"><h2>Your cart</h2><button class="icon" onclick="toggleCart(false)">×</button></div><div id="cartItems"></div><div class="drawer-bottom"><div class="total"><b>Total</b><b id="cartTotal"></b></div><a class="button wide" href="${root}checkout.html">SECURE CHECKOUT</a></div></aside><button class="chat-bubble" onclick="toggleChat()" aria-label="Talk to ForgeBot">✦</button><section class="chat" id="chat"><div class="chat-head">ForgeBot <button onclick="toggleChat()">×</button></div><div class="messages" id="messages"><p class="bot">Hi, I’m ForgeBot. Ask about shipping, returns, fitment or ceramic coating.</p></div><form onsubmit="chat(event)"><input aria-label="Your message" placeholder="Ask a question"><button>Send</button></form></section>`);document.querySelector('.menu').onclick=()=>document.querySelector('.nav').classList.toggle('open');renderCart();}
function card(p){return `<article class="card">${image(p)}<div class="card-body"><small>${p.brand||'AUTOFORGE'} · ${p.type}</small><h3><a href="product.html?id=${p.id}">${p.name}</a></h3><p>${p.desc}</p><div class="price-row"><b>${AF.money(p.price)} ${p.mrp?`<del>${AF.money(p.mrp)}</del>`:''}</b><button class="add" onclick="add('${p.id}')">ADD</button></div></div></article>`}
function add(id){let c=AF.get('af_cart',[]),x=c.find(i=>i.id===id);x?x.qty++:c.push({id,qty:1});AF.set('af_cart',c);renderCart();document.getElementById('cartCount').textContent=c.reduce((n,i)=>n+i.qty,0)}
function renderCart(){let c=AF.get('af_cart',[]), total=c.reduce((n,i)=>n+(product(i.id)?.price||0)*i.qty,0);let target=document.getElementById('cartItems');if(target)target.innerHTML=c.length?c.map(i=>{let p=product(i.id);return `<div class="cart-item"><span>${p.name}<small>${AF.money(p.price)} × ${i.qty}</small></span><span><button onclick="changeCart('${i.id}',-1)">−</button> ${i.qty} <button onclick="changeCart('${i.id}',1)">+</button></span></div>`}).join(''):'Your cart is empty.';if(document.getElementById('cartTotal'))document.getElementById('cartTotal').textContent=AF.money(total);if(document.getElementById('cartCount'))document.getElementById('cartCount').textContent=c.reduce((n,i)=>n+i.qty,0)}
function changeCart(id,d){let c=AF.get('af_cart',[]);let x=c.find(i=>i.id===id);x.qty+=d;if(x.qty<1)c=c.filter(i=>i!==x);AF.set('af_cart',c);renderCart()};function toggleCart(x){document.getElementById('cartDrawer').classList.toggle('open',x===undefined?!document.getElementById('cartDrawer').classList.contains('open'):x);document.querySelector('.backdrop').classList.toggle('open',document.getElementById('cartDrawer').classList.contains('open'))}
function logout(){localStorage.removeItem('af_session');location.href='index.html'}
function toggleChat(){document.getElementById('chat').classList.toggle('open')};function chat(e){e.preventDefault();let i=e.target.querySelector('input'),q=i.value.trim(),m=document.getElementById('messages');if(!q)return;m.insertAdjacentHTML('beforeend',`<p class="me">${q}</p><p class="bot typing">ForgeBot is typing…</p>`);i.value='';setTimeout(()=>{m.querySelector('.typing').remove();let ql=q.toLowerCase(),a=ql.includes('ship')?'Most orders ship in 1–2 business days and arrive in 3–7 days.':ql.includes('return')?'Unused products can be requested for return within 7 days of delivery.':ql.includes('fit')?'Share your car make, model and year; our fitment team will confirm before dispatch.':ql.includes('ceramic')||ql.includes('booking')?'Choose ceramic coating, select your car and a slot, then our technician visits your address.':'I can help with shipping, returns, fitment, product care and doorstep ceramic coating.';m.insertAdjacentHTML('beforeend',`<p class="bot">${a}</p>`);m.scrollTop=m.scrollHeight},550)}
/* DEMO ONLY. This uses simple keyword matching. For real AI-powered answers, connect this to the Anthropic API (or similar) from a secure backend — never call an AI API directly from client-side JS with an exposed key. */
